version: "3"
services:
  api:
    build: ./api/
    command: sh -c "sleep 20s; uvicorn api:app --host 0.0.0.0"
    ports:
      - "8000:8000"
    depends_on:
      - db
  etl:
    container_name: etl
    build: ./etl/
    command: sh -c "sleep 10s; python3 ./etl.py"
    depends_on:
      - db
  db:
    container_name: db
    build: ./db/
    restart: always
    environment:
      MYSQL_DATABASE: db
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 33066:3306